### PR TITLE
update to crystal 1.0.0

### PR DESCRIPTION
**Pull request by Cuda-Chen**

### CODE REVIEW

**Comment by c910335** [comment]
Travis CI 過氣了
你要幫我設定 GitHub Actions 嗎

**Comment by Cuda-Chen** [comment]
Yes, I can help you settings GitHub Actions.

**Comment by Cuda-Chen** [comment]
Added in https://github.com/c910335/crie/pull/2

**Comment by c910335** [comment]
Rebase 一下讓這裡跑 GitHub Actions 吧

**Pull request merged**
